config/routes.rb
SmartEnergy::Application.routes.draw do
  mount RailsAdmin::Engine => '/admin', :as => 'rails_admin'

  resources :households do
    member do
      get "gas_usage", as: :gas_usage
      get "power_usage", as: :power_usage
      get "readings", as: :readings
    end
  end

  match 'survey' => 'households#chart_drill'

  

  devise_for :users

  root :to => 'households#power_usage'

end

app/models/household.rb
class Household < ActiveRecord::Base
  has_many :users
  has_many :power_records
  has_many :gas_records

  NAME_COMBINATIONS = {
    "power_records_amount" => "Electricity usage",
    "power_records_carbon_result" => "CO2 generated",
    "power_records_carbon_intensity" => "Carbon intensity",
    "power_records_price" => "Energy price",
    "power_records_energy_cost" => "Energy cost",
    "gas_records_amount" => "Gas usage",
    "gas_records_carbon_result" => "CO2 generated"
  }

  UNITS=["day", "month", "year", "all"]

  UNIT_COMBINATIONS = {
    "amount" => {
      "day" => { "unit" => "Wh", "divider" => 1 },
      "month" => { "unit" => "kWh", "divider" => 1000 },
      "year" => { "unit" => "MWh", "divider" => 1000000 },
      "all" => { "unit" => "MWh", "divider" => 1000000 },
    },
    "carbon_result" => {
      "day" => { "unit" => "grams CO2", "divider" => 1 },
      "month" => { "unit" => "kg CO2", "divider" => 1000 },
      "year" => { "unit" => "kg CO2", "divider" => 1000 },
      "all" => { "unit" => "tons CO2", "divider" => 1000000 },
    },
    "carbon_intensity" => {
      "day" => { "unit" => "grams/kWh", "divider" => 1 },
      "month" => { "unit" => "grams/kWh", "divider" => 1 },
      "year" => { "unit" => "grams/kWh", "divider" => 1 },
      "all" => { "unit" => "grams/kWh", "divider" => 1 },
    },
    "price" => {
      "day" => { "unit" => "pence/kWh", "divider" => 1 },
      "month" => { "unit" => "pence/kWh", "divider" => 1 },
      "year" => { "unit" => "pence/kWh", "divider" => 1 },
      "all" => { "unit" => "pence/kWh", "divider" => 1 },
    },
    "energy_cost" => {
      "day" => { "unit" => "pence", "divider" => 1 },
      "month" => { "unit" => "pounds", "divider" => 100 },
      "year" => { "unit" => "pounds", "divider" => 100 },
      "all" => { "unit" => "pounds", "divider" => 100 },
    }
  }

  COLORS = {
    "amount" => "#89A54E",
    "carbon_intensity" => "#AA4643",
    "carbon_result" => "#89A54E",
    "price" => "#AA4643",
    "energy_cost" => "#4572A7"
  }

  def readings(energy, date, unit, axis="amount", all=false)
    categories = []
    data = []
    # type = energy == "gas" ? "gas_records" : "power_records"
    type = energy
    series_name = NAME_COMBINATIONS["#{type}_#{axis}"]
    units = UNIT_COMBINATIONS[axis][unit]["unit"]
    divider = UNIT_COMBINATIONS[axis][unit]["divider"]
    color = COLORS[axis]
    operation = "sum"

    case unit
    when "day"
      chart_name = date.strftime("%d %B %Y")
      group = "hour"
      frmt_time = "%H:%M"
      child_unit = "all"
      level = 3
    when "month"
      chart_name = date.strftime("%B %Y")
      group = "day"
      frmt_time = "%d"
      child_unit = "day"
      level = 2
    when "year"
      chart_name = date.strftime("%Y")
      group = "month"
      frmt_time = "%B"
      child_unit = "month"
      level = 1
    else
      chart_name = "All time usage"
      group = "year"
      frmt_time = "%Y"
      child_unit = "year"
      level = 0
    end

    case axis 
    when "carbon_intensity"
      operation = "AVG"
    when "price"
      operation = "AVG"
    end

    if unit=="all"
      readings = self.send(type).aggregate_records(group, axis, operation, all)
    else
      readings = self.send(type).within(date, unit).aggregate_records(group, axis, operation, all)
    end
    sum=0
    props = UNIT_COMBINATIONS.keys - ["carbon_intensity", "price"]
    totals = Hash.new(0)
    readings.each do |record|
      record_date = DateTime.strptime(record["period_date"], "%F %T")
      categories << record_date.strftime(frmt_time)
      if all
        results = {}
        props.each do |prop|
          results[prop] = [(record[prop].to_f/UNIT_COMBINATIONS[prop][unit]["divider"]).round(2), UNIT_COMBINATIONS[prop][unit]["unit"]]
          totals[prop] += record[prop].to_f 
        end
      end
      p record.attributes
      p record[axis]
      data << { date: record_date.strftime("%F"),
                y: (record[axis].to_f/divider).round(2),
                results: all ? results : false,
                unit: child_unit,
                chart_name: chart_name,
                level: level-1,
                type: type,
                axis: axis }
    end

    return {
      units: units,
      # make the name be describing - Electricity, CO2, Gas, money
      chart_name: chart_name,
      series_name: series_name  + " " + chart_name,
      data: data,
      categories: categories,
      level: level,
      color: color,
      totals: totals.each{ |k,v| totals[k] = "#{(v/UNIT_COMBINATIONS[k][next_unit(unit)]["divider"]).round(2)} #{UNIT_COMBINATIONS[k][next_unit(unit)]["unit"]}" }
    }    
  end

  private
  def next_unit(unit)
    return "all" if unit=="all"
    UNITS[(UNITS.index(unit)+1)%UNITS.length]
  end
end

app/controllers/households_controller.rb
class HouseholdsController < ApplicationController
  before_filter :authenticate_user!

  # GET /households
  # GET /households.json
  def index
    @households = Household.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @households }
    end
  end

  # GET /households/1
  # GET /households/1.json
  def show
    @household = Household.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @household }
    end
  end

  # GET /households/new
  # GET /households/new.json
  def new
    @household = Household.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @household }
    end
  end

  # GET /households/1/edit
  def edit
    @household = Household.find(params[:id])
  end

  # POST /households
  # POST /households.json
  def create
    @household = Household.new(params[:household])

    respond_to do |format|
      if @household.save
        format.html { redirect_to @household, notice: 'Household was successfully created.' }
        format.json { render json: @household, status: :created, location: @household }
      else
        format.html { render action: "new" }
        format.json { render json: @household.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /households/1
  # PUT /households/1.json
  def update
    @household = Household.find(params[:id])

    respond_to do |format|
      if @household.update_attributes(params[:household])
        format.html { redirect_to @household, notice: 'Household was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @household.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /households/1
  # DELETE /households/1.json
  def destroy
    @household = Household.find(params[:id])
    @household.destroy

    respond_to do |format|
      format.html { redirect_to households_url }
      format.json { head :no_content }
    end
  end

  def gas_usage
    @type = "power"
    chart_drill
  end

  def power_usage
    @household = params[:id].present? ? Household.find(params[:id]) : Household.last 
    @type = "power_records"
    @date = Time.now
    @unit = "all"
    @axis = "energy_cost"
    @data = @household.readings(@type, @date, @unit, "energy_cost", true)

    respond_to do |format|
      format.html
    end
  end

  def chart
    generate_chart

    respond_to do |format|
      format.html { render :chart}
      format.js { render "chart.js" }
    end
  end

  def chart_drill
    @household = Household.find(params[:id]) 
    @type = "power_records"
    @date = Time.now
    @unit = "all"
    @axis = "energy_cost"
    @data = @household.readings(@type, @date, @unit, "energy_cost", true)

    respond_to do |format|
      format.html { render :chart_drill}
    end
  end

  def readings
    @household = Household.find(params[:id])
    @data = @household.readings(params[:type], Date.strptime(params[:date], "%F"), params[:unit], params[:axis], params[:all]=="true")

    render json: @data.to_json
  end

  private

  def calculate_ticks
    diff = @end_time - @start_time
    if diff < 2
      @unit = "hour"
      @interval = 3600*1000
    elsif diff < 32
      @unit = "day"
      @interval = 24*3600*1000
    else
      @unit = "week"
      @interval = 7*24*3600*1000
    end
  end

  def generate_chart
    @household = Household.find(params[:id])
    if params[:search]
      @start_time = DateTime.strptime(params[:search][:date_from], "%Y-%m-%d")
      @end_time = DateTime.strptime(params[:search][:date_to], "%Y-%m-%d")
    else
      @start_time = EnergyRecord.first.period_end.to_date
      @end_time = @start_time + 7.days
    end

    calculate_ticks
    # @data = @household.get_readings_for(@type, @start_time, @end_time, @unit, false)
  end
end

app/helpers/households_helper.rb
module HouseholdsHelper
end

app/views/households/_buttons_js.html.erb
<%= javascript_tag do %>
  $(function(){
    var description = $(".row#description"),
        survey = $(".row#survey iframe"),
        graph = $("#graph");

    $("#proceed_eval").click(function(argument) {
      description.slideUp("slow");
      survey.attr("height", 260);
      graph.slideDown("slow");
      $("#proceed_eval").hide();
    });

    $("#proceed_final").click(function(argument) {
      survey.attr("height", 1000);
      graph.slideUp("slow");
      $("#proceed_eval").show();
    });

    // graph.show();
    // description.hide();
    // survey.hide();

  });
<% end %>

app/views/households/_form.html.erb
<%= form_for(@household) do |f| %>
  <% if @household.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@household.errors.count, "error") %> prohibited this household from being saved:</h2>

      <ul>
      <% @household.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/households/_show_js.html.erb
<%= javascript_tag do %>
  $(function(){
    var fromField = $("#date_from");
    var toField = $("#date_to")
    // var fromField = $("#date_from");
    $(".day_picker").datepicker({
      format: 'yyyy-mm-dd',
      autoclose: true,
      weekStart: 1,
      startView: 2
    });
    $("#search_date_from").datepicker().on('changeDate', function(ev){
      var start = $(this).val();
      $("#search_date_to")[0].value = start;
      $("#search_date_to").datepicker("setStartDate", start);
      $("#search_date_to").datepicker("update");
    });

    chart = new Highcharts.Chart({
      chart: { renderTo: "chart_container",
               defaultSeriesType: "<%= current_user.chart_type %>" },
      title: { text: "Usage" },
      xAxis: { type: "datetime",
                labels: {
                  rotation: -60,
                  align: "right",
                  style: {
                      fontSize: "13px",
                      fontFamily: "Verdana, sans-serif"
                  }
                },
                tickInterval: <%= @interval %>,
                gridLineColor: "#bfbfc0",
                gridLineDashStyle: "ShortDash",
                gridLineWidth: "1" },
      yAxis: {
        title: { text: "watts" }
      }, 
      series: [{
        name: "Period 2", 
        data: <%= @household.get_readings_for(@type, @start_time, @end_time, @unit, false) %>,
        pointStart: <%= @start_time.to_time.to_i*1000 %>,
        pointInterval: <%= @interval %>
      }]
    });

    function changeType(series, newType) {
      var dataArray = [],
          points = series.data;
      series.chart.addSeries({
          type: newType,
          name: series.name,
          color: series.color,
          data: series.options.data,
          pointInterval: series.pointInterval,
          pointStart: series.xData[0]
      }, false);
      
      series.remove();
    }
    $('#chart_type').change(function() {
      for(i = 0, l = chart.series.length; i < l; ++i) {
        var series = window.chart.series[0],
            newType = $(this).val();
        changeType(series, newType);
      }
    });
    $('#chartType').change(function(){
        chart.changeSeriesType(this.value);
    });
  });
<% end %>

app/views/households/_show_js_drill.html.erb
<%= javascript_tag do %>
  function setChart(drilldown, type, pointClick, yAxis) {
    if(pointClick){
      chart.setTitle({
        text: drilldown.chart_name
      });
      chart.xAxis[0].setCategories(drilldown.categories);
      // chart.series[0].remove();
      while(chart.series.length > 0)
        chart.series[0].remove(true);
      $(".totals#date").html(drilldown.chart_name);
      $.each(drilldown.totals, function(property, value) {
        $(".totals#"+property).html(value);        
      });
    }
    chart.yAxis[yAxis].setTitle({text: drilldown.units});

    chart.addSeries({
      name: drilldown.series_name,
      data: drilldown.data,
      level: drilldown.level,
      color: drilldown.color,
      type: type,
      yAxis: yAxis,
      dataLabels: {
        enabled: false,
        color: drilldown.color
      }
    });
  }

  function init_graph() {
    $.getJSON("<%= readings_household_path(@household.id) %>", 
      { date: "<%= @date %>",
        unit: "<%= @unit %>",
        type: "<%= @type %>",
        axis: "<%= @axis %>",
        all: true,
        id: <%= @household.id %> }, 
      function(drilldown) {
        setChart(drilldown, chartType, true, 0);
      }
    );

    comparison_container.slideUp("slow");
    $("#prev_period").val("Previous");
    $("#next_period").val("Next");
    $(".graph_nav").attr("disabled", 1);
  }
  function writePeriod (unit, date, type) {
    $(".period-shown #unit").val(unit);
    $(".period-shown #date").val(date);
    $(".period-shown #type").val(type);
    $("label#last_period span").text("Previous " + unit);
    $("label#next_period_comp span").text("Next " + unit);

    if($("#unit").val()=="all"){
      comparison_container.slideUp("slow");
      $(".graph_nav").attr("disabled", 1);
      var button_txt = ""
    }else{
      comparison_container.slideDown("slow");
      $(".graph_nav").removeAttr("disabled");
      var button_txt = unit
    }

    $("#prev_period").val("Previous " + button_txt);
    $("#next_period").val("Next " + button_txt);
  }

  function changeType(series, newType) {
    var dataArray = [],
        points = series.data;
    series.chart.addSeries({
      type: newType,
      name: series.name,
      color: series.color,
      data: series.options.data,
      pointInterval: series.pointInterval,
      pointStart: series.xData[0]
    }, false);
    
    series.remove();
  }

  function previous_period() {
    var date = new Date($(".period-shown #date").val()),
        unit = $("#unit").val();

    if(unit=="year")
      date.setMonth(date.getMonth() - 12);
    else
      if(unit=="month")
        date.setMonth(date.getMonth() - 1);
      else
        date.setDate(date.getDate() - 1);

    return date.toISOString().slice(0,10)
  }
  function next_period() {
    var date = new Date($(".period-shown #date").val()),
        unit = $("#unit").val();

    if(unit=="year")
      date.setMonth(date.getMonth() + 12);
    else
      if(unit=="month")
        date.setMonth(date.getMonth() + 1);
      else
        date.setDate(date.getDate() + 1);

    return date.toISOString().slice(0,10)
  }

  function disableAxes() {
    $.each($(".comparison_toggler"), function(index, value) {
      if(value.checked){
        chart.yAxis[0].series[1].destroy();
        value.checked=false;
      }
    });
  }

  function enableAxes() {
    $.each($(".chart-toggler"), function(index, value) {
      if(value.checked)
        toggleAxis(value, false);
    });
  }

  function toggleAxis(toggler,click) {
    var axis = toggler.value,
        axis_n = parseInt($(toggler).attr("axis_n")),
        color = $(toggler).attr("color"),
        type = $(toggler).attr("series_type");

    if(toggler.checked){
      $.getJSON("<%= readings_household_path(@household.id) %>", 
        { date: $(".period-shown #date").val(),
          unit: $(".period-shown #unit").val(),
          type: $(".period-shown #type").val(),
          axis: axis,
          all: false,
          id: <%= @household.id %> },
        function (result) {
          setChart(result, type, false, axis_n);
        }
      );
    }else{
      chart.yAxis[axis_n].series[0].destroy();
      if(click)
        chart.yAxis[axis_n].destroy();
    }
  }

  function drilldown(point) {
    $.getJSON("<%= readings_household_path(@household.id) %>", 
      { date: point.date,
        unit: point.unit,
        type: point.type,
        axis: point.axis,
        all: true,
        id: <%= @household.id %> }, 
      function(result) {
        setChart(result, chartType, true, 0);
      }
    );    
  }

  $(function(){
    chartType = "<%= current_user.try(:chart_type) || 'column' %>";

    comparison_container = $("#comparison_container");
    prev_period_button = $("input#prev_period");
    next_period_button = $("input#next_period");

    $("#reset_graph").click(function() {
      disableAxes();
      init_graph();
      $(".chart-toggler").attr("checked", false);
    })

    $('#chart_type').change(function() {
      chartType = $(this).val();
      for(i = 0, l = chart.series.length; i < l; ++i) {
        var series = window.chart.series[0],
            newType = chartType;
        changeType(series, newType);
      }
    });

    $(".chart-toggler").change(function() {
      toggleAxis(this, true);
    });

    $(".graph_nav").click(function() {
      if(this.id=="prev_period")
        var new_date = previous_period();
      else
        var new_date = next_period()
      writePeriod($(".period-shown #unit").val(),
                  new_date, 
                  $(".period-shown #type").val());
      disableAxes();
      drilldown({
        unit: $(".period-shown #unit").val(),
        date: new_date, 
        type: $(".period-shown #type").val(),
        axis: "energy_cost"
      });
      enableAxes();
    });

    var comparison_series=[1,2];

    $(".comparison_toggler").change(function () {
      if(this.id=="last_period"){
        var period = previous_period()
            color = "#800080";
            index = 0;
      }else{
        var period = next_period(),
            color = "#FF7F00";
            index = 1;
      }
      if(this.checked){
        $.getJSON("<%= readings_household_path(@household.id) %>",  
          { date: period,
            unit: $(".period-shown #unit").val(),
            type: $(".period-shown #type").val(),
            axis: "energy_cost",
            all: true,
            id: <%= @household.id %> },
          function (result) {
            result["color"] = color;
            setChart(result, "column", false, 0);
            comparison_series[index]=chart.yAxis[0].series[chart.yAxis[0].series.length-1];
          }
        );

      }else{
        comparison_series[index].destroy();
      }
    });

    var colors = Highcharts.getOptions().colors;
    var main_axes = {},
        extra_axes = {};
   
    chart = new Highcharts.Chart({
      chart: {
        renderTo: 'chart_container',
        type: chartType
      },
      subtitle: {
        text: 'Click on a column to view monthly usage. Click again to view daily usage.'
      },
      xAxis: {
        labels: {
          rotation: -45,
          align: "right",
          style: {
            fontSize: "13px",
            fontFamily: "Verdana, sans-serif"
          }
        },
      },
      yAxis: [
        {
          type: "column",
          title: {
            text: "<%= raw @data[:units] %>",
            style: {
              color: '#4572A7'
            }
          },
          labels: {
            style: {
              color: '#4572A7'
            }
          }
        },
        {
          title: {
            text: "Carbon generated",
            style: {
              color: '#89A54E'
            }
          },
          min: -200,
          labels: {
            style: {
              color: '#89A54E'
            }
          },
          opposite: true,
          showEmpty: false
        },
        {
          plotOptions: {
            type: "spline"
          },
          title: {
            text: "Carbon intensity",
            style: {
              color: '#AA4643'
            }
          },
          min: -200,
          labels: {
            style: {
              color: '#AA4643'
            }
          },
          opposite: true,
          showEmpty: false
        }
      ],
      plotOptions: {
        series: {
          cursor: 'pointer',
          point: {
            events: {
              click: function() {
                var params = {
                  date: this.date,
                  unit: this.unit,
                  type: this.type,
                  axis: this.axis
                }
                if(this.axis!='energy_cost') //|| (this.series.color == "#800080"))
                  return
                writePeriod(this.unit, this.date, this.type);
                disableAxes();
                drilldown(params);
                enableAxes();
              }
            }
          },
          marker: {
            symbol: "circle"
          },
          dataLabels: {
            // enabled: true,
            // color: colors[0],
            // style: {
            //    fontWeight: 'bold'
            // },
            formatter: function() {
              return this.y;
            }
            // rotation: -60
          }               
        }
      },
      tooltip: {
        formatter: function() {
          var point = this.point;
          s = '<b>' + point.category + ' ' + point.chart_name + '</b> <br/>';

          if(point.results){
            s +=  "Cost: " + point.y + " " + point.series.yAxis.axisTitle.text + ' <br/>';
            s += "Usage: " + point.results.amount.join(" ") + ' <br/>';
            s += "Carbon footprint: " + point.results.carbon_result.join(" ") + ' <br/>';
          }else{
            s += point.series.name + ": " + point.y + " " + point.series.yAxis.axisTitle.text;
          }

          return s;
        }
      },
      series: [{}],
      exporting: {
        enabled: false
      }
    });

    init_graph();
  });
<% end %>

app/views/households/buttons_js.html.erb
<%= javascript_tag do %>
  $(function(){
    $("#proceed_eval").click(fun)
  });
<% end %>

app/views/households/chart.html.erb
<div class="row">
  <div class="span6">
    <%= form_tag @type=="gas" ? gas_usage_household_path : power_usage_household_path, method: :get do %>
      From
      <%= text_field "search", "date_from", 
                              value: @start_time.to_date, 
                              class: "day_picker input-small start_date" %>
      To
      <%= text_field "search", "date_to", 
                              value: @end_time.to_date, 
                              class: "day_picker input-small end_date" %>
      <%= submit_tag "GO" %>
    <% end %>
  </div>
  <div class="span6">
    <%= form_tag @type=="gas" ? gas_usage_household_path : power_usage_household_path, method: :get, remote: true do %>
      From
      <%= text_field "search", "date_from", 
                              value: @start_time.to_date, 
                              class: "day_picker input-small start_date" %>
      To
      <%= text_field "search", "date_to", 
                              value: @end_time.to_date, 
                              class: "day_picker input-small end_date" %>
      <%= submit_tag "Add" %>
    <% end %>
  </div>

  <div class="span12">
    <div id="chart_container">
    </div>
    <%= select  "chart", 
                "type", 
                CHART_TYPES, 
                selected: current_user.chart_type %>
  </div>
</div>
<%= render partial: "show_js.html.erb" %>

app/views/households/chart.js.erb
chart.addSeries({
  name: "Period 2",
  data: <%= @household.get_readings_for(@type, @start_time, @end_time, @unit, false) %>,
  pointStart: chart.series[0].xData[0],// <%= @start_time.to_time.to_i*1000 %>
  pointInterval: <%= @interval %>
})

app/views/households/edit.html.erb
<h1>Editing household</h1>

<%= render 'form' %>

<%= link_to 'Show', @household %> |
<%= link_to 'Back', households_path %>

app/views/households/index.html.erb
<h1>Listing households</h1>

<table>
  <tr>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @households.each do |household| %>
  <tr>
    <td><%= link_to 'Show', household %></td>
    <td><%= link_to 'Edit', edit_household_path(household) %></td>
    <td><%= link_to 'Destroy', household, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Household', new_household_path %>

app/views/households/new.html.erb
<h1>New household</h1>

<%= render 'form' %>

<%= link_to 'Back', households_path %>

app/views/households/power_usage.html.erb
<div class="span12">
  <div id="graph">
    <div class="row">
      <div class="span10">
        <div class="row">
          <div id="chart_container" class="span10" style="height: 500px;">
          </div>
        </div>
        <div id="chart_controls" class="row">
          <div class="period-shown">
            <%= hidden_field_tag "type", @type %>
            <%= hidden_field_tag "date", @date %>
            <%= hidden_field_tag "unit", @unit %>
          </div>
          <div class="span3">
            <input class="graph_nav pull-left btn-primary btn span2" disabled="true" id="prev_period" type="button" value="Previous"> 
          </div>
          <div class="span4">
            <span class="pull-left">
              Toggle: 
            </span>
            <%= check_box_tag "carbon_intensity_toggler", "carbon_intensity", false, class: "pull-left chart-toggler", color: 5, axis_n: 2, series_type: "line" %>
            <%= label_tag "carbon_intensity_toggler", "CO2 intensity", class: "pull-left" %>
            
            <%= check_box_tag "carbon_toggler", "carbon_result", false, class: "pull-left chart-toggler", color: 6, axis_n: 1, series_type: "spline" %>
            <%= label_tag "carbon_toggler", "CO2 emissions", class: "pull-left" %>
          </div>
          <div class="span2" style="display: none;" >
            <%= check_box_tag "usage_toggler", "amount", false, class: "pull-left chart-toggler", color: 6, axis_n: 1, series_type: "spline" %>
            <%= label_tag "usage_toggler", "Energy usage", class: "pull-left" %>      
          </div>
          <div class="span2" style="display: none;" >
            <%= check_box_tag "price_toggler", "price", false, class: "pull-left chart-toggler", color: 5, axis_n: 2, series_type: "line" %>
            <%= label_tag "price_toggler", "Energy price", class: "pull-left" %>
          </div>
          <div class="span3">
            <input class="graph_nav pull-right btn-primary btn span2" disabled="true" id="next_period" type="button" value="Next"> 
          </div>
        </div>
      </div>
      <div class="span2">
        <input class="span2 btn-success btn" id="reset_graph" type="button" value="Reset graph"> 

        <div class="span2 right_container">
          Totals for the period:
          <span id="date" class="totals">All time</span> <br/>
          Cost: <br/> 
          <span id="energy_cost" class="totals">###</span> <br/>
          Usage: <br/> 
          <span id="amount" class="totals">###</span> <br/>
          Carbon footprint: <br/> 
          <span id="carbon_result" class="totals">###</span> <br/>        
        </div>

        <div id="comparison_container" style="display: none;" class="span2 right_container">
          Compare to: <br/>
          <label id="last_period" class="checkbox">
            <%= check_box_tag "last_period", "", false, class: "comparison_toggler" %>
            <span>Previous year</span>
          </label>
          <label id="next_period_comp" class="checkbox">
            <%= check_box_tag "next_period_comp", "", false, class: "comparison_toggler" %>
            <span>Next year</span>
          </label>
        </div>
      </div>
    </div>
  
  </div>
</div>
<%= render partial: "show_js_drill.html.erb" %>
<%= render partial: "buttons_js.html.erb" %>

app/views/households/show.html.erb
<h1>Dashboard</h1>
<div class="row">
  <div class="span12">
    <ul>
      <li>
        <%= link_to "Power usage", power_usage_household_path(current_user.household) %>
        <ul>
          <li>
            <%= link_to "For yesterday", power_usage_household_path(current_user.household, {
              search: {
                date_from: "2011-02-28",
                date_to:   "2011-02-28"
              }
            }) %>
          </li>
          <li>
            <%= link_to "For last week", power_usage_household_path(current_user.household, {
              search: {
                date_from: "2011-02-28",
                date_to:   "2011-03-07"
              }
            }) %>
          </li>
          <li>
            <%= link_to "For last month", power_usage_household_path(current_user.household, {
              search: {
                date_from: "2011-02-28",
                date_to:   "2011-03-28"
              }
            }) %>
          </li>
        </ul>
      </li>
      <li>
        <%= link_to "Gas usage", gas_usage_household_path(current_user.household) %>
        <ul>
          <li>
            <%= link_to "For yesterday", power_usage_household_path(current_user.household, {
              search: {
                date_from: "2011-02-28",
                date_to:   "2011-02-28"
              }
            }) %>
          </li>
          <li>
            <%= link_to "For last week", power_usage_household_path(current_user.household, {
              search: {
                date_from: "2011-02-28",
                date_to:   "2011-03-07"
              }
            }) %>
          </li>
          <li>
            <%= link_to "For last month", power_usage_household_path(current_user.household, {
              search: {
                date_from: "2011-02-28",
                date_to:   "2011-03-28"
              }
            }) %>
          </li>
        </ul>
      </li>
    </ul>
  </div>
</div>